export const SceneMap = [
    {
        id: 1,
        prevSceneName: '/',
        currentSceneName: '/',
        nextSceneName: '/Scene9Screen1',
        hidePrev: true,
        hideNext: true,
        assetID: '',
    },
    {
        id: 2,
        prevSceneName: '/',
        currentSceneName: '/Scene9Screen1',
        nextSceneName: '/Scene9Screen2',
        hidePrev: true,
        hideNext: false,
        assetID: '',
    },
    {
        id: 3,
        prevSceneName: '/Scene9Screen1',
        currentSceneName: '/Scene9Screen2',
        nextSceneName: '/Scene9Screen3',
        hidePrev: false,
        hideNext: false,
        assetID: '',
    },
    {
        id: 4,
        prevSceneName: '/Scene9Screen2',
        currentSceneName: '/Scene9Screen3',
        nextSceneName: '/Scene9Screen4',
        hidePrev: false,
        hideNext: false,
        assetID: '',
    },
    {
        id: 5,
        prevSceneName: '/Scene9Screen3',
        currentSceneName: '/Scene9Screen4',
        nextSceneName: '/Scene9Screen5',
        hidePrev: false,
        hideNext: false,
        assetID: '',
    },
    {
        id: 6,
        prevSceneName: '/Scene9Screen4',
        currentSceneName: '/Scene9Screen5',
        nextSceneName: '/Scene10',
        hidePrev: false,
        hideNext: true,
        assetID: '',
    },
    {
        id: 7,
        prevSceneName: '/Scene9Screen5',
        currentSceneName: '/Scene10',
        nextSceneName: '/Game3Screen1',
        hidePrev: true,
        hideNext: true,
        assetID: '',
    },
    {
        id: 8,
        prevSceneName: '/Scene10',
        currentSceneName: '/Game3Screen1',
        nextSceneName: '/Game3Screen2',
        hidePrev: true,
        hideNext: true,
        assetID: '',
    },
    {
        id: 9,
        prevSceneName: '/Game3Screen1',
        currentSceneName: '/Game3Screen2',
        nextSceneName: '/Game3Screen3',
        hidePrev: true,
        hideNext: true,
        assetID: '',
    },
    {
        id: 10,
        prevSceneName: '/Game3Screen2',
        currentSceneName: '/Game3Screen3',
        nextSceneName: '/Game3Screen4',
        hidePrev: true,
        hideNext: true,
        assetID: '',
    },
    {
        id: 11,
        prevSceneName: '/Game3Screen3',
        currentSceneName: '/Game3Screen4',
        nextSceneName: '/Game3Screen5',
        hidePrev: true,
        hideNext: true,
        assetID: '',
    },
    {
        id: 12,
        prevSceneName: '/Game3Screen4',
        currentSceneName: '/Game3Screen5',
        nextSceneName: '/Game3Screen6',
        hidePrev: true,
        hideNext: true,
        assetID: '',
    },
    {
        id: 13,
        prevSceneName: '/Game3Screen5',
        currentSceneName: '/Game3Screen6',
        nextSceneName: '/Game3Screen7',
        hidePrev: true,
        hideNext: true,
        assetID: '',
    },
    {
        id: 14,
        prevSceneName: '/Game3Screen6',
        currentSceneName: '/Game3Screen7',
        nextSceneName: '/WellDone',
        hidePrev: true,
        hideNext: true,
        assetID: '',
    },
    {
        id: 15,
        prevSceneName: '/Game3Screen7',
        currentSceneName: '/WellDone',
        nextSceneName: '/',
        hidePrev: true,
        hideNext: true,
        assetID: '',
    }
]